#!/usr/bin/env dash

START_DIR=$(pwd)

if [ -d $HOME/.vim/autoload ]; then
	cd $HOME/.vim/autoload
	curl -so pathogen.vim \
		https://raw.github.com/tpope/vim-pathogen/HEAD/autoload/pathogen.vim
fi

if [ -d "$HOME/.vim/bundle" ]; then
	for bundle in "$HOME/.vim/bundle/"*
	do
		if [ -d "$bundle/.git" ]; then
			printf "Working on %s...\n" ${bundle##*/}
			cd "$bundle"; git pull 2>/dev/null
		fi
	done
fi

cd $START_DIR
