#!/usr/bin/env ruby
#require 'optiflag'

deps = {}
ARGV.each {|arg| deps[arg] = []}

def check_em(deps)
  installed = %x{brew list}.split("\n").map {|pkg| pkg + '.rb'}
  brew = %x{brew --prefix}.chomp + '/Library/Formula'
  Dir.chdir(brew)
  installed.each do |formula|
    File.open(formula, 'r').each do |line|
      deps.keys.each do |dep|
        if line.match(/depends_on\s+('|")#{dep}('|")/)
          deps[dep].push(formula)
        end
      end
    end
  end
end

def show_em(deps)
  deps.keys.each do |item|
    if deps[item].empty?
      puts "No dependents of #{item}"
    else
      puts "Installed dependents of #{item}:"
      deps[item].each do |dep|
        print "    %s\n" % dep.gsub('.rb', '')
      end
    end
  end
end

if deps.empty?
  puts "Usage: $0 item1 item2 item3"
  puts "You must give me at least one item to check on."
  exit
else
  check_em(deps)
  show_em(deps)
end
