filetype off
"call pathogen#runtime_append_all_bundles()
"call pathogen#helptags()
runtime bundle/vim-unbundle/unbundle.vim

" Most general settings first
set nocompatible            " Vim rather than Vi settings; must go first
set noeb                    " Set no audio or visual error beep
set bs=indent,eol,start     " Backspace over everything in insert mode
set history=500             " Keep 50 lines of command line history
set scrolloff=3             " A little breathing room
set number                  " Always show line numbers
set tags=./tags;

" Set items for view @ bottom of windows
set ruler                   " Show the cursor position all the time
set showcmd                 " Display incomplete commands
set showmode                " Display current mode
set ls=2                    " Always show status bar

" Remove overbright matching of parentheses
let g:loaded_matchparen = 1

" Syntax basics
syntax on
filetype plugin indent on

" Do POSIX right
let g:is_posix = 1

" Text basics
"set wrap
"set linebreak
"let &showbreak = '+++ '
set textwidth=75
set colorcolumn=80
set formatoptions=tcqn1
set fo-=c
set fo-=r
set fo-=o
set tabstop=4
set softtabstop=4
set shiftwidth=4
set expandtab               " Use spaces for tabs
set number

" Use the same symbols as TextMate for tabstops and EOLs
set listchars=tab:▸-,trail:·,eol:¬
set list

" Editor layout {{{
set termencoding=utf-8
set encoding=utf-8
set laststatus=2            " Always put a status line in, even
                            " if there is only one window
set showtabline=2           " Show a tabbar on top, always
set cmdheight=2             " Use a status bar that is 2 rows high
" }}}

" An easier leader than \
let mapleader = ","

" Search and regex settings
set ignorecase
set smartcase
set gdefault
set incsearch               " Do incremental searching
set hlsearch                " Highlight all matches in a search
nnoremap <silent> <leader><space> :noh<cr>

" Don't use Ex mode, use Q for formatting
map Q gq

" Enable mouse
set mouse=a

" Use Dim for my colorscheme
set t_Co=256
colorscheme inkpot

" Fix placement of backups and swap files
set backup
set backupdir=$HOME/.vim_backups,/tmp
set directory=/tmp,$HOME/.vim_backups

" Vim 7.3, now with persistent undo
set undofile            " Test the persistent unto feature
set undodir=$HOME/.vim_undo,/tmp

" Use ack instead of grep
set grepprg=ack\ --nogroup\ --column
set grepformat=%f:%l:%c:%m

" Tell Vim to print using US-sized paper, not A4
set printoptions:paper:letter,header:0,syntax:n
set printfont:Consolas

" From http://tuxtraining.com/2008/11/11/exploring-vim-configurations
set hidden
nnoremap ' `
nnoremap ` '
set title
set scrolloff=3
set shortmess=atI
nnoremap <silent> <leader>p :set invpaste<CR>
imap <leader>/ <C-X>/
imap <C-_>     <C-X><SPACE>
imap <leader>w <M-e>

" let g:delimitMate_excluded_regions = "Comment,String"

" status line hijinks
set statusline=%<%f\ %h%m%r%y%{\"[\".(&fenc==\"\"?&enc:&fenc).\"]\"}
\%{exists('g:loaded_rbenv')?rbenv#statusline_ft_ruby():''}
\%{exists('g:loaded_perlbrew')?perlbrew#statusline_ft_perl():''}
\%{exists('g:loaded_fugitive')?fugitive#statusline():''}
\%=%-14.(%l,%c%V%)\ %P

" Shortcut to rapidly toggle `set list`
nnoremap <silent><leader>l :set list!<CR>

runtime macros/matchit.vim
"
" Make sure Markdown files are properly recognized
autocmd BufNewFile,BufNew,BufRead *.markdown,*.md,*.mdown,*.mkd,*.mkdn
\    setlocal filetype=markdown
