filetype off
call pathogen#runtime_append_all_bundles()
call pathogen#helptags()

" Most general settings first
set nocompatible            " Set Vim rather than Vi settings; must go first
set noeb                    " Set no audio or visual error beep
set bs=indent,eol,start     " Backspace over everything in insert mode
set history=500	            " Keep 50 lines of command line history
set scrolloff=3             " A little breathing room
set number                  " Always show line numbers

" Set items for view @ bottom of windows
set ruler                   " Show the cursor position all the time
set showcmd                 " Display incomplete commands
set showmode                " Display current mode
set ls=2                    " Always show status bar

" Remove overbright matching of parentheses
let g:loaded_matchparen = 1

" Syntax basics
syntax on
filetype plugin indent on
set autoindent
set smartindent

" Text basics
set wrap
set linebreak
set colorcolumn=85
set formatoptions=qn1
let &showbreak = '+++ '
set tabstop=4               " A reasonable set of tab defaults
set softtabstop=4
set shiftwidth=4
set expandtab               " Use spaces for tabs
set number

" Editor layout {{{
set termencoding=utf-8
set encoding=utf-8
set laststatus=2            " tell VIM to always put a status line in, even
                            "    if there is only one window
set showtabline=2           " show a tabbar on top, always
set cmdheight=2             " use a status bar that is 2 rows high
" }}}

" An easier leader than \
let mapleader = ","

" Search and regex settings
nnoremap / /\v
vnoremap / /\v
set ignorecase
set smartcase
set gdefault
set incsearch               " Do incremental searching
set showmatch
set hlsearch                " Highlight all matches in a search
nnoremap <silent> <leader><space> :noh<cr>
nnoremap <tab> %
vnoremap <tab> %

" Matchy match
set showmatch              " Show matching brackets
set matchtime=1             " But turn it off quickly

" Don't use Ex mode, use Q for formatting
map Q gq

" Use desert for my colorscheme
colorscheme desert

" Make tab in v-mode indent code
vmap <tab> >gv
vmap <s-tab> <gv

" Make tab in normal mode indent code
nmap <tab> I<tab><esc>
nmap <s-tab> ^i<bs><esc>

" Fix placement of backups and swap files
set backup
set backupdir=$HOME/.vim_backups,/tmp
set directory=/tmp,$HOME/.vim_backups

" Vim 7.3, now with persistent undo
set undofile
set undodir=$HOME/.vim_undo,/tmp

" Some Perl voodoo: insert Perl base & set filetype
imap ,perl #!/usr/bin/env perl<CR>use strict;
    \<CR>use warnings;<CR><esc>:set filetype=perl<ENTER>i

" Tell Vim to print using US-sized paper, not A4
set printoptions:paper:letter,header:0
" Easier way to get into normal mode?
imap jk <Esc>

" Stuff from http://tuxtraining.com/2008/11/11/exploring-vim-configurations
set hidden
nnoremap ' `
nnoremap ` '
let mapleader = ","
set title
set scrolloff=3
nmap <silent> <leader>n :nohlsearch<CR>
set listchars=tab:>-,trail:·,eol:$
nmap <silent> <leader>s :set nolist!<CR>
set shortmess=atI
nmap <silent> <leader>pa :set invpaste<CR>
imap <C-l> =><Space>

let g:liquid_highlight_types = ["html","erb=eruby","html+erb=eruby.html"]
let g:closetag_html_style = 1
let g:delimitMate_excluded_regions = "Comment,String"

" status line hijinks
set statusline=%<%f\ %h%m%r%y
\%{exists('g:loaded_rvm')?Rvm#statusline_ft_ruby():''}
\%{exists('g:loaded_fugitive')?fugitive#statusline():''}
\%=%-14.(%l,%c%V%)\ %P

" Modeline experiment
" Append modeline after last line in buffer.
" Use substitute() instead of printf() to handle '%%s' modeline in LaTeX
" files.
function! AppendModeline()
  let l:modeline = printf(" vim: set ts=%d sw=%d tw=%d :",
        \ &tabstop, &shiftwidth, &textwidth)
  let l:modeline = substitute(&commentstring, "%s", l:modeline, "")
  call append(line("$"), l:modeline)
endfunction
nnoremap <silent> <Leader>ml :call AppendModeline()<CR>

" Shortcut to rapidly toggle `set list`
nmap <leader>l :set list!<CR>

" Use the same symbols as TextMate for tabstops and EOLs
set listchars=tab:▸\ ,eol:¬

" Comment and uncomment visual blocks quickly
vmap <leader>- :s/\v^(\s*)(.*)$/\1# \2/<CR>:nohl<CR>
vmap <leader>_ :s/\v^(\s*)# (.*)$/\1\2/<CR>:nohl<CR>
